/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllBooksHere: typeof import('./src/components/all-books/all-books-here.vue')['default']
    AllBooksTags: typeof import('./src/components/all-books/all-books-tags.vue')['default']
    BorrowFinish: typeof import('./src/components/borrow/borrow-finish.vue')['default']
    BorrowIng: typeof import('./src/components/borrow/borrow-ing.vue')['default']
    CardAlterable: typeof import('./src/components/card-alterable.vue')['default']
    CardAlterableTest: typeof import('./src/components/card-alterable-test.vue')['default']
    Favorite_detail: typeof import('./src/components/favorite/favorite_detail.vue')['default']
    Favorite_simplified: typeof import('./src/components/favorite/favorite_simplified.vue')['default']
    HeadPortrait: typeof import('./src/components/head-portrait.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NRate: typeof import('naive-ui')['NRate']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    RecomendArt: typeof import('./src/components/recommend/recomend-art.vue')['default']
    RecomendBiography: typeof import('./src/components/recommend/recomend-biography.vue')['default']
    RecomendBizarre: typeof import('./src/components/recommend/recomend-bizarre.vue')['default']
    RecomendEconomics: typeof import('./src/components/recommend/recomend-economics.vue')['default']
    RecomendFiction: typeof import('./src/components/recommend/recomend-fiction.vue')['default']
    RecomendForeignLiterature: typeof import('./src/components/recommend/recomend-foreign-literature.vue')['default']
    RecomendHumanity: typeof import('./src/components/recommend/recomend-humanity.vue')['default']
    RecomendLiterature: typeof import('./src/components/recommend/recomend-literature.vue')['default']
    RecomendMasterwork: typeof import('./src/components/recommend/recomend-masterwork.vue')['default']
    RecomendPeotry: typeof import('./src/components/recommend/recomend-peotry.vue')['default']
    RecomendScienceFiction: typeof import('./src/components/recommend/recomend-science-fiction.vue')['default']
    RecomendSuspense: typeof import('./src/components/recommend/recomend-suspense.vue')['default']
    RecomendYouth: typeof import('./src/components/recommend/recomend-youth.vue')['default']
    RecommendLatest: typeof import('./src/components/recommend/recommend-latest.vue')['default']
    RecommendSlideshow: typeof import('./src/components/recommend/recommend-slideshow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCompo: typeof import('./src/components/search-compo.vue')['default']
    UserCenterConpo: typeof import('./src/components/user-center/user-center-conpo.vue')['default']
    UserPic: typeof import('./src/components/user-center/user-pic.vue')['default']
  }
}
